export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  ADJUST_QTY: "ADJUST_QTY",
  LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM",
  INCREMENT: "INCREMENT",
};
